project1/App1/urls.py
from django.urls import path
from . import views
app_name= "App1"
urlpatterns = [
    path('<int:couse_id>/',views.detail,name='detail'),
    path('',views.Courses,name='home-page'),
    path('<int:couse_id>/yourchoice', views.yourchoice, name='yourchoice'),

]

project1/project1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App1.urls')),
]

project1/App1/models.py
from django.db import models
import datetime
from django.utils import timezone
class Allcourses(models.Model):
    #creating column name in table or defining class variable
    coursename = models.CharField(max_length = 200)
    insname = models.CharField(max_length = 100)
    startedfrom = models.DateTimeField('Started From')
    def __str__(self):
        return self.coursename
    def was_published_recently(self):
        now = timezone.now()
        return now-datetime.timedelta(days=1)<=self.startedfrom<=now

class details(models.Model):
    #when we deleted any course from Allcourses class then it automatically deleted its details from details class
    couse = models.ForeignKey(Allcourses,on_delete=models.CASCADE)
    ct = models.CharField(max_length=500)
    your_choice = models.BooleanField(default=False)
    def __str__(self):
        return str(self.ct)

project1/App1/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, Http404
from . models  import Allcourses
from django.template import loader

# Create your views here.
def Courses(request):
    ac = Allcourses.objects.all()
    template = loader.get_template('App1/Courses.html')
    context = {
        'ac':ac,
    }
    return HttpResponse(template.render(context,request))


def detail(request,couse_id):
    course = get_object_or_404(Allcourses,pk = couse_id)
    return render(request,'App1/details.html',{'course':course})
    # page = None
    # try:
    #     course = Allcourses.objects.get(pk=couse_id)
    #     page = render(request, 'App1/details.html', {'course': course})
    # except Allcourses.DoesNotExist:
    #     page =  render(request,'App1/404.html')
    # return page

def yourchoice(request, couse_id):
    course = get_object_or_404(Allcourses, pk = couse_id)
    try:
        selected_ct = course.details_set.get(pk = request.POST['choice'])
    except (KeyError,Allcourses.DoesNotExist):
        return render(request,'App1/details.html',{'course':course,'error_message':"Select a valid option"})
    else:
        selected_ct.your_choice = True
        selected_ct.save()
        return render(request,'App1/details.html',{'course':course})

project1/App1/templates/App1/Courses.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Home</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Courses<span class="sr-only">(current)</span></a></li>
        <li><a href="#">Details</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<h1> Welcome to Programmers Choice</h1>
<img src="https://cdn.pixabay.com/photo/2015/06/08/15/11/typewriter-801921_960_720.jpg" width="600px" height="300px">
<ol>
    {%for x in ac%}
    <li><a href="/{{x.id}}">{{x.coursename}}</a></li>
    {% endfor %}
</ol>
<!--project1/App1/templates/App1/Courses.html-->

project1/App1/templates/App1/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

{%if course.pk is 1%}
<h1><a href="https://www.javatpoint.com">{{course.coursename}}</a></h1>
<h2>{{course.insname}}</h2>
<ul>
    {%for x in Allcourses.set.all%}
    <li>{{x.ct}}</li>
    {% endfor %}

</ul>
{%elif course.pk is 2%}
<h1><a href="https://www.javatpoint.com">{{course.coursename}}</a></h1>
<h2>{{course.insname}}</h2>
elif course.pk is 3%}
<h1><a href="https://www.javatpoint.com">{{course.coursename}}</a></h1>
<h2>{{course.insname}}</h2>
{%endif%}

{%if error_message%}
<p><strong>{{error_message}}</strong></p>
{%endif%}
<form action="{%url 'App1:yourchoice' course.id%}" method="POST">
    {% csrf_token%}
    {% for choice in course.details_set.all %}
     <input type="radio" name = "choice" id="choice{%forloop.counter%}" value="{{course.id}}">
     <label for="choice{%forloop.counter%}">{{choice.ct}}</label><br>
    {%endfor%}

    <input type="submit" value = "Submit">

</form>
</body>
</html>